//CARD
//CARD
export const GET_LOCALSTOREG_CARD = "GET_LOCALSTOREG_CARD";
export const DELETED_ALL_CARD = "DELETED_ALL_CARD";

export const CREATE_CARD = "CREATE_CARD";
export const CREATE_CARD_INPUT_CHECKED = "CREATE_CARD_INPUT_CHECKED";
export const REDACT_CARD_TITLE = "REDACT_CARD_TITLE";
export const DELETED_CARD = "DELETED_CARD";

//TASK
//TASK

export const CREATE_TASK = "CREATE_TASK";
export const DELETE_TASK = "DELETE_TASK";
export const REDACT_NAME_TASK = "REDACT_NAME_TASK";

//ITEM
//ITEM

export const CREATE_ITEM_TASK = "CREATE_ITEM_TASK";
export const TOGGLE_CHECKBOX_ITEM_TASK = "TOGGLE_CHECKBOX_ITEM_TASK";
export const REDACT_NAME_ITEM_TASK = "REDACT_NAME_ITEM_TASK";
export const DELETED_ITEM_TASK = "DELETED_ITEM_TASK";

//FilterTasks in Card
//FilterTasks in Card

export const FILTER_TASK_ALPHABET = "FILTER_TASK_ALPHABET";
export const FILTER_TASKS_COMPLETED = "FILTER_TASKS_COMPLETED";
export const FILTER_TASKS_COMPLETED_REVERSE = "FILTER_TASKS_COMPLETED_REVERSE";
export const FILTER_TASK_ALPHABET_REVERSE = "FILTER_TASK_ALPHABET_REVERSE";
