//HEADER CREATE-ACTIONS 
export const TOGGLE_CHECKED_BOARD = "TOGGLE_CHECKED_BOARD";
export const TOGGLE_CHECKED_STAR = "TOGGLE_CHECKED_STAR";
export const TOGGLE_CHECKED_WIDGET = "TOGGLE_CHECKED_WIDGET";
export const TOGGLE_CHECKED_WORKPLACE = "TOGGLE_CHECKED_WORKPLACE";
export const TOGGLE_CHECKED_SHAER = "TOGGLE_CHECKED_SHAER";
export const TOGGLE_CHECKED_UPDATE = "TOGGLE_CHECKED_UPDATE";
export const TOGGLE_CHECKED_AUTOMATION = "TOGGLE_CHECKED_AUTOMATION";
export const TOGGLE_CHECKED_FILTER = "TOGGLE_CHECKED_FILTER";
export const TOGGLE_CHECKED_MENU = "TOGGLE_CHECKED_MENU";